const constants = {
	FETCH_EXCHANGE_RATE_START: 'FETCH_EXCHANGE_RATE_START',
	FETCH_EXCHANGE_RATE_SUCCESS: 'FETCH_EXCHANGE_RATE_SUCCESS',
	FETCH_EXCHANGE_RATE_FAILURE: 'FETCH_EXCHANGE_RATE_FAILURE',
}

export default constants